version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'online_store'
      # MYSQL_USER: 'db_user'
      # MYSQL_PASSWORD: 'db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_vol:/var/lib/mysql
volumes:
  db_vol: